FROM node:20.19.2

# Set working directory
WORKDIR /app

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=ecoville
ENV NODE_ENV=production

# Copy package files first
COPY package*.json pnpm-lock.yaml ./

# Install pnpm
RUN npm install -g pnpm@latest

# Install dependencies
RUN pnpm install

# Copy source code and config files
COPY . .

# Build TypeScript
RUN pnpm build

# Expose port
EXPOSE 9001

# Command to run the compiled application
CMD ["npm",'run', "start"]
