services:
  server:
    build: .
    ports:
      - "9001:9001"
    env_file:
      - .env
    networks:
      - restraunt-network
    volumes:
      - ./:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 5

networks:
  restraunt-network:
    driver: bridge