FROM node:20.19.2

# Set working directory
WORKDIR /app

# Set environment variables
ENV MONGO_INITDB_ROOT_USERNAME=root
ENV MONGO_INITDB_ROOT_PASSWORD=ecoville
ENV NODE_ENV=production

# Copy package.json and package-lock.json
COPY package.json pnpm-lock.yaml ./

# Clear any existing cache and install dependencies

RUN pnpm install --frozen-lockfile --prod=false

# RUN pnpm build

# Copy the rest of the application code
COPY . .

# Expose port
EXPOSE 9001

# Command to run the application
CMD ["pnpm", "start"]
